# Generated by Django 2.2.17 on 2025-01-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('salary', models.FloatField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
